version: '3.3'

services:
  backend-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 8091:5432
  jupyter-client:
    # image : jupyter/datascience-notebook
    build: .
    ports:
      - "8888:8888"
    depends_on: 
      - backend-db
    volumes:
      - ./mynote:/home/jovyan/work
  load-db:
    build : ./load-db
    depends_on:
      - backend-db
    volumes:
      - ./load-db:/load-db
    command: bash -c "tail -f /dev/null"

    # command: >
    #   bash -c "mlflow server --host 0.0.0.0 
    #   --backend-store-uri postgresql://postgres:mypassword@backend-db:5432/postgres 
    #   --default-artifact-root ./model_artifacts_new6"
    # command: bash -c "tail -f /dev/null"