version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dbsto
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 8091:5432
  load-db:
    build : ./load-db
    depends_on:
      - db
    volumes:
      - ./load-db:/load-db
    command: bash -c "python /load-db/load-db.py"
  jupyter-client:
    # image : jupyter/datascience-notebook
    build: ./jupyter-client
    ports:
      - "8888:8888"
    depends_on: 
      - db
    volumes:
      - ./jupyter-client/mynotebooks:/home/jovyan/work